[package]
name = "hpcrypt-kdf"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hpcrypt-core = { workspace = true }
hpcrypt-hash = { workspace = true }
hpcrypt-mac = { workspace = true }
hpcrypt-aead = { workspace = true, optional = true }
subtle = { workspace = true }
zeroize = { workspace = true }
sha2 = { version = "0.10", default-features = false }

[dev-dependencies]
hex-literal = { workspace = true }
wycheproof = "0.6"
serde_json = "1.0"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
argon2 = "0.5.3"
blake2 = "0.10.6"

[features]
default = ["std"]
std = ["hpcrypt-core/std", "hpcrypt-hash/std", "hpcrypt-mac/std", "hpcrypt-aead?/std"]
alloc = ["hpcrypt-core/alloc", "hpcrypt-hash/alloc", "hpcrypt-mac/alloc", "hpcrypt-aead?/alloc"]
quic-header-protection = ["dep:hpcrypt-aead"]
