[package]
name = "hpcrypt-mac"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Cryptographic primitives for HPCrypt"
keywords.workspace = true
categories.workspace = true

[dependencies]
hpcrypt-core = { workspace = true }
hpcrypt-cipher = { workspace = true }
hpcrypt-hash = { workspace = true }
subtle = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }

[features]
default = ["std", "alloc"]
std = ["hpcrypt-core/std", "hpcrypt-cipher/std", "hpcrypt-hash/std", "alloc"]
alloc = ["hpcrypt-core/alloc", "hpcrypt-cipher/alloc", "hpcrypt-hash/alloc"]
