[package]
name = "hpcrypt-mac"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Cryptographic primitives for HPCrypt"
keywords.workspace = true
categories.workspace = true

[dependencies]
hpcrypt-core = { workspace = true }
hpcrypt-aead = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }
wycheproof = "0.6"
serde_json = "1.0"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }

[features]
default = ["std"]
std = ["hpcrypt-core/std", "hpcrypt-aead/std"]
alloc = ["hpcrypt-core/alloc", "hpcrypt-aead/alloc"]
