[package]
name = "hpcrypt-quic"
version.workspace = true
edition.workspace = true

[dependencies]
hpcrypt-core = { workspace = true }
hpcrypt-aead = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }

[features]
default = ["std"]
std = ["hpcrypt-core/std"]
alloc = ["hpcrypt-core/alloc"]
